name: wrf_processing
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.7.3
  - matplotlib==3.1.3
  - numpy==1.17.2
  - pandas==0.25.1
  - xarray==0.14.0
  - scipy==1.3.1
  - netcdf4==1.5.1.2
  - dask==2.6.0
  - windrose==1.6.7
  - shapely==1.7.0
  - wrf-python=1.3.2
